lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET_KEY)%'  # Hoặc đường dẫn tuyệt đối đến private key nếu không sử dụng env
    public_key: '%env(JWT_PUBLIC_KEY)%'  # Hoặc đường dẫn tuyệt đối đến public key
    pass_phrase: '%env(JWT_PASSPHRASE)%'  # Passphrase nếu bạn có
    token_ttl: 3600
