# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: 'My API'
            description: 'This is the API documentation for my Symfony app.'
            version: '1.0.0'
        paths:
            /api/v1/books:
                get:
                    summary: 'Get a list of books'
                    responses:
                        200:
                            description: 'List of books'
                            content:
                                application/json:
                                    schema:
                                        type: array
                                        items:
                                            type: string
        security:
            - bearerAuth: [ ]
